---
- name: Load OS-specific vars
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
      paths:
        - "vars"

- name: include task setup_debian.yml
  import_tasks: setup_debian.yml
  when: ansible_os_family == "Debian"

- name: include task setup_redhat.yml
  import_tasks: setup_redhat.yml
  when: ansible_os_family == "RedHat"

- name: include task configure.yml
  import_tasks: configure.yml

- name: include task databases.yml
  import_tasks: databases.yml
  when:
    - mariadb_databases is defined
    - mariadb_replication_role != "replica"

- name: include task users.yml
  import_tasks: users.yml
  when:
    - mariadb_users is defined
    - mariadb_replication_role != "replica"

- name: include task replication_master.yml
  import_tasks: replication_master.yml
  when: mariadb_replication_role == "master"

- name: include task replication_replica.yml
  import_tasks: replication_replica.yml
  when:
    - not ansible_check_mode
    - mariadb_replication_role == "replica"

- name: include task backup.yml
  import_tasks: backup.yml
  when: mariadb_backup_db
