---
- name: Converge
  hosts: all
  gather_facts: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files: testvars.yml

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=true cache_valid_time=600

  roles:
    - role: ansible-role-mariadb
