---
name: molecule

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 2"

jobs:
  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-18.04
            playbook: converge.yml
          - distro: ubuntu-18.04
            playbook: converge-mdbf.yml
          - distro: ubuntu-20.04
            playbook: converge.yml
          - distro: ubuntu-20.04
            playbook: converge-mdbf.yml
          - distro: ubuntu-20.10
            playbook: converge.yml
          - distro: ubuntu-20.10
            playbook: converge-mdbf.yml
          - distro: debian-10
            playbook: converge.yml
          - distro: debian-10
            playbook: converge-mdbf.yml
          - distro: debian-sid
            playbook: converge.yml

    steps:
      # see https://github.com/actions/virtual-environments/issues/3536#issuecomment-858433636)
      # - name: Set rights for podman
      #   run: sudo chmod o+rwx -R /sys/fs/cgroup/systemd
      - uses: actions/checkout@v2
      - name: Install requirements
        run: |
          sudo python3 -m pip install --upgrade pip
          sudo python3 -m pip install -r requirements.txt
      - name: Run molecule
        # using sudo see https://github.com/actions/virtual-environments/issues/3536
        run: sudo molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: ${{ matrix.playbook }}
