---
name: MDBF deployment

on:
  push:
    paths:
      - .github/workflows/test_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  pull_request:
    paths:
      - .github/workflows/test_mdbf.yml
      - requirements.txt
      - "files/**"
      - "handlers/**"
      - "molecule/default/**"
      - "tasks/**"
      - "templates/**"
      - "vars/**"
  schedule:
    - cron: "10 5 * * 2"

jobs:
  molecule-mdbf-pkg:
    name: MDBF
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu-18.04
          - ubuntu-20.04
          - ubuntu-22.04
          - ubuntu-23.04
          - debian-10
          - debian-11
          - debian-12
          - debian-sid
          - fedora-37
          - fedora-38
          - almalinux-8
          - almalinux-9
          - rockylinux-8
          - rockylinux-9
        mariadb-version:
          - "10.4"
          - "10.5"
          - "10.6"
          - "10.7"
          - "10.8"
          - "10.9"
          - "10.10"
          - "10.11"
          - "11.0"
          - "11.1"
          - "11.2"
        exclude:
          - distro: ubuntu-22.04
            mariadb-version: 10.4
          - distro: ubuntu-22.04
            mariadb-version: 10.5
          - distro: ubuntu-23.04
            mariadb-version: 10.4
          - distro: ubuntu-23.04
            mariadb-version: 10.5
          - distro: ubuntu-23.04
            mariadb-version: 10.6
          - distro: ubuntu-23.04
            mariadb-version: 10.7
          - distro: ubuntu-23.04
            mariadb-version: 10.8
          - distro: ubuntu-23.04
            mariadb-version: 10.9
          - distro: ubuntu-23.04
            mariadb-version: 10.10
          - distro: debian-11
            mariadb-version: 10.4
          - distro: debian-12
            mariadb-version: 10.4
          - distro: debian-12
            mariadb-version: 10.5
          - distro: debian-12
            mariadb-version: 10.6
          - distro: debian-12
            mariadb-version: 10.7
          - distro: debian-12
            mariadb-version: 10.8
          - distro: debian-12
            mariadb-version: 10.9
          - distro: debian-12
            mariadb-version: 10.10
          - distro: debian-sid
            mariadb-version: 10.4
          - distro: debian-sid
            mariadb-version: 10.5
          - distro: fedora-37
            mariadb-version: 10.4
          - distro: fedora-37
            mariadb-version: 10.5
          - distro: fedora-38
            mariadb-version: 10.4
          - distro: fedora-38
            mariadb-version: 10.5
          - distro: fedora-38
            mariadb-version: 10.7
          - distro: almalinux-9
            mariadb-version: 10.4
          - distro: rockylinux-9
            mariadb-version: 10.4

    steps:
      - uses: actions/checkout@v4
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
      # This is necessary on GH Actions to allow running systemd in rootless containers
      # see: https://github.com/actions/virtual-environments/issues/3536
      # see: https://github.com/ansible-community/molecule/discussions/3155
      - name: Start systemd user service
        run: |
          loginctl enable-linger $(whoami)
          sleep 1
      - name: Run molecule
        run: molecule test
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: ${{ matrix.distro }}
          MOLECULE_PLAYBOOK: mdbf.yml
          MARIADB_VERSION: ${{ matrix.mariadb-version }}
